# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test-project:
    name: Run unit tests for the project.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
      - name: Setup Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies.
        run: npm ci
      - name: Run lint.
        run: npm run lint -- --ignore-pattern "examples"
      - name: Run project unit tests.
        run: npm run test
  test-examples:
    name: Run unit tests for ${{ matrix.example }}.
    strategy:
      matrix:
        example:
          - react
          - vanilla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
      - name: Setup Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies.
        working-directory: ./examples/${{ matrix.example }}
        run: npm install
      - name: Run lint.
        working-directory: ./examples/${{ matrix.example }}
        run: npm run lint --if-present
      - name: Run unit tests.
        working-directory: ./examples/${{ matrix.example }}
        run: npm run test
      - name: Run build.
        working-directory: ./examples/${{ matrix.example }}
        run: npm run build
